default["chef-marketplace"]["db_host"] = "localhost"
default["chef-marketplace"]["db_name"] = "marketplace"
default["chef-marketplace"]["db_user"] = "root"
default["chef-marketplace"]["db_pass"] = "ilikerandompasswords"
default["chef-marketplace"]["db_prefix"] = ""
default["chef-marketplace"]["cron_key"] = "iwlBW_YhoVc5daJjnhkCQsSNs-cLGop4U6j04bBEYJ8"
default["chef-marketplace"]["code_url"] = "https://github.com/booz-allen-hamilton/marketplace/archive/master.tar.gz"
